---
- name: Create PostgreSQL users
  community.general.postgresql_user:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    state: present
  become: true
  become_user: postgres
  loop: "{{ postgresql_users }}"
  loop_control:
    label: "{{ item.name }}"

- name: Grant all privileges on database to users
  community.postgresql.postgresql_privs:
    db: "{{ postgresql_database_name }}"
    privs: ALL
    type: schema
    objs: public
    role: "{{ item.name }}"
  become: true
  become_user: postgres
  loop: "{{ postgresql_users }}"
  loop_control:
    label: "{{ item.name }}"
...
