---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
  become: true
  changed_when: false

- name: Upgrade all packages
  ansible.builtin.apt:
    upgrade: dist
    autoremove: true
  become: true
