---
- name: Ensure the AWX namespace exists
  kubernetes.core.k8s:
    kubeconfig: /etc/kubernetes/admin.conf
    api_version: v1
    kind: Namespace
    name: "{{ awx_namespace }}"
    state: present
  become: true
