---
- name: Create the AWX namespace
  ansible.builtin.command: "kubectl create namespace {{ awx_namespace }}"
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  become: true
  register: awx_namespace_result
  changed_when: awx_namespace_result.rc == 0
  failed_when:
    - awx_namespace_result.rc != 0
    - "'AlreadyExists' not in awx_namespace_result.stderr"
