---
- name: Template the AWX admin password secret
  ansible.builtin.template:
    src: admin-password-secret.yaml.j2
    dest: /etc/kubernetes/awx-admin-password-secret.yaml
    mode: "0600"
  become: true

- name: Apply the AWX admin password secret
  ansible.builtin.command: kubectl apply -f /etc/kubernetes/awx-admin-password-secret.yaml
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  become: true
  changed_when: false

- name: Template the AWX postgres configuration secret
  ansible.builtin.template:
    src: postgres-configuration-secret.yaml.j2
    dest: /etc/kubernetes/awx-postgres-configuration-secret.yaml
    mode: "0600"
  become: true

- name: Apply the AWX postgres configuration secret
  ansible.builtin.command: kubectl apply -f /etc/kubernetes/awx-postgres-configuration-secret.yaml
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  become: true
  changed_when: false
