---
- name: Apply the AWX admin password secret
  kubernetes.core.k8s:
    kubeconfig: /etc/kubernetes/admin.conf
    state: present
    definition: "{{ lookup('ansible.builtin.template', 'admin-password-secret.yaml.j2') }}"
  become: true
  no_log: true

- name: Apply the AWX postgres configuration secret
  kubernetes.core.k8s:
    kubeconfig: /etc/kubernetes/admin.conf
    state: present
    definition: "{{ lookup('ansible.builtin.template', 'postgres-configuration-secret.yaml.j2') }}"
  become: true
  no_log: true
