---
dependency:
  name: galaxy
driver:
  name: vagrant
  parallel: false
  provider:
    name: virtualbox
platforms:
  - name: rockylinux9
    box: bento/rockylinux-9
    memory: 4096
    cpus: 2
    groups:
      - single
    instance_raw_config_args:
      - "vm.boot_timeout = 600"
    config_options:
      ssh.insert_key: false
  - name: rockylinux10
    box: bento/rockylinux-10
    memory: 4096
    cpus: 2
    groups:
      - single
    instance_raw_config_args:
      - "vm.boot_timeout = 600"
    config_options:
      ssh.insert_key: false
  - name: ubuntu2404
    box: bento/ubuntu-24.04
    memory: 4096
    cpus: 2
    groups:
      - single
    instance_raw_config_args:
      - "vm.boot_timeout = 600"
    config_options:
      ssh.insert_key: false
  - name: ubuntu2604
    box: bento/ubuntu-26.04
    memory: 4096
    cpus: 2
    groups:
      - single
    instance_raw_config_args:
      - "vm.boot_timeout = 600"
    config_options:
      ssh.insert_key: false
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: "../../.."
  playbooks:
    prepare: prepare.yml
verifier:
  name: ansible
ansible:
  cfg:
    ssh_connection:
      retries: 5
    defaults:
      timeout: 30
