---
- name: Deploy AWX
  hosts: single:masters
  become: true
  vars:
    awx_namespace: "awx"
    awx_operator_version: "2.19.1"
    awx_name: "awx"
    awx_service_type: "ClusterIP"
    awx_ingress_enabled: true
    awx_ingress_host: "awx.devlab.local"
    awx_admin_user: "admin"
    awx_admin_password: "AnotherChangeMe123!"
    awx_replicas: 1
    awx_task_cpu_request: "100m"
    awx_task_mem_request: "128Mi"
    awx_task_cpu_limit: "2000m"
    awx_task_mem_limit: "4Gi"
    awx_web_cpu_request: "100m"
    awx_web_mem_request: "128Mi"
    awx_web_cpu_limit: "1000m"
    awx_web_mem_limit: "4Gi"
    awx_ee_cpu_request: "100m"
    awx_ee_mem_request: "128Mi"
    awx_ee_cpu_limit: "1000m"
    awx_ee_mem_limit: "4Gi"
    awx_postgres_host: "{{ groups['postgresql'][0] }}"
    awx_postgres_database: "awx"
    awx_postgres_user: "awx"
    awx_postgres_password: "ChangeMe123!"

  tasks:
    - name: AWX
      ansible.builtin.include_role:
        name: redhatguru.general.awx
