---
- name: Install Kubernetes
  hosts: single:masters:workers
  become: true
  vars:
    kubernetes_version: "1.35"
    kubernetes_pod_network_cidr: "192.168.10.0/16"
    kubernetes_dashboard_enabled: true
    kubernetes_dashboard_admin_user: true
    kubernetes_hardening_enabled: true
    kubernetes_harden_kubelet: true
    kubernetes_harden_network_policy: true

  tasks:
    - name: Kubernetes
      ansible.builtin.include_role:
        name: redhatguru.general.kubernetes
