---
- name: Install Kubernetes
  hosts: single:masters:workers
  become: true
  vars:
    kubernetes_version: "1.35"
    kubernetes_pod_network_cidr: "192.168.10.0/16"
    kubernetes_dashboard_enabled: true
    kubernetes_dashboard_admin_user: true
    kubernetes_hardening_enabled: true
    kubernetes_harden_kubelet: true
    kubernetes_harden_network_policy: true
    kubernetes_etcd_heartbeat_interval: "250"
    kubernetes_etcd_election_timeout: "2500"
    kubernetes_apiserver_etcd_timeout: "10s"
    kubernetes_wait_timeout: 600

  tasks:
    - name: Kubernetes
      ansible.builtin.include_role:
        name: redhatguru.general.kubernetes
