---
- name: Deploy PostgreSQL
  hosts: postgresql
  become: true
  vars:
    postgresql_version: "17"
    postgresql_user: "awx"
    postgresql_user_password: "ChangeMe123!"
    postgresql_database_name: "awx"
    postgresql_root_password: "ChangeMeToo123!"
    postgresql_allow_subnet: "10.0.0.0/24"

  tasks:
    - name: PostgreSQL
      ansible.builtin.include_role:
        name: redhatguru.general.postgresql
      tags:
        - install
        - createdb
        - createusr
        - hardening
