---
name: ansible-lint

on:
  pull_request:
    branches:
      - main

jobs:
  ansible-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install yamllint
        run: pip install yamllint

      - name: Run yamllint
        run: yamllint .

      - name: Run ansible-lint
        uses: ansible/ansible-lint@main
        with:
          args: "-c ansible-lint.cfg ."
