name: ansible-lint

on:
  pull_request:
    branches:
      - main

jobs:
  ansible-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Run ansible-lint
        uses: ansible/ansible-lint@main
        with:
          args: "-c ansible-lint.cfg ."
